services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runtime
    container_name: clash-speedtest-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend/configs:/app/configs:ro
      - ./backend/output:/app/output
    environment:
      LOG_LEVEL: info
    networks:
      - clash-speedtest-net

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: runtime
    container_name: clash-speedtest-frontend
    restart: unless-stopped
    ports:
      - "3000:8080"
    environment:
      VITE_API_URL: http://backend:8080
    depends_on:
      - backend
    networks:
      - clash-speedtest-net

networks:
  clash-speedtest-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
