port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090

proxies:
  - name: "test-proxy-1"
    type: http
    server: httpbin.org
    port: 80

  - name: "test-proxy-2"
    type: http
    server: example.com
    port: 80

proxy-groups:
  - name: "test-group"
    type: select
    proxies:
      - "test-proxy-1"
      - "test-proxy-2"

rules:
  - MATCH,test-group